// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Caml_format = require("rescript/lib/js/caml_format.js");

console.log("Hello, World!");

var input = Fs.readFileSync("day1.txt", "utf8");

function split_elves(str) {
  var arr = str.split("\n\n");
  console.log("Number of Elves: " + String(arr.length));
  return arr;
}

var elves = split_elves(input);

function sum_calories(inp) {
  return inp.split("\n").map(Caml_format.int_of_string).reduce((function (acc, v) {
                return acc + v | 0;
              }), 0);
}

var sum = sum_calories(Caml_array.get(elves, 0));

console.log("calories of first elf: " + String(sum) + "");

exports.input = input;
exports.split_elves = split_elves;
exports.elves = elves;
exports.sum_calories = sum_calories;
exports.sum = sum;
/*  Not a pure module */
